# Nome do arquivo do jogo
JOGO = main.py

# Alvos do Makefile
.PHONY: all jogo clean

# Alvo para executar o jogo
jogo:
	python3 -m pgzero $(JOGO)

# Alvo para limpar arquivos temporários
clean:
	@rm -f temp.py
